// GENERATED by scripts/sync-codex-models.ts — do not edit by hand.
// Source: openai/codex release tag rust-v0.153.4 (GitHub releases/latest). Codex sends the
// whole semver (major.minor.patch) as client_version to /models; the endpoint
// gates slugs by it, so re-run `pnpm sync:codex-models` when codex ships a release.
export const DEFAULT_OPENAI_CODEX_CLIENT_VERSION = "0.153.4";
