// Generated by pnpm sync:client-versions; do not edit by hand.
// Source: https://api.github.com/repos/openai/codex/releases/latest
export const DEFAULT_OPENAI_CODEX_CLIENT_VERSION = "0.160.1" as const;
