#!/usr/bin/env bash
set -euo pipefail

cd "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

mode=setup
if [[ "${1:-}" == "--cli" ]]; then
  mode=cli
  shift
fi
if [[ $# -ne 0 ]]; then
  echo "Usage: $0 [--cli]" >&2
  exit 2
fi

if ! docker compose version >/dev/null 2>&1; then
  echo "Docker Compose is required: https://docs.docker.com/get-docker/" >&2
  exit 1
fi

if [[ ! -f .env ]]; then
  HELM_UID=$(id -u)
  HELM_GID=$(id -g)
  HELM_PORT_VALUE=${HELM_PORT:-8080}
  umask 077

  if [[ "$mode" == "cli" ]]; then
    command -v openssl >/dev/null 2>&1 || {
      echo "OpenSSL is required to generate the admin and encryption credentials." >&2
      exit 1
    }
    HELM_ADMIN_USER_VALUE=${HELM_ADMIN_USER:-admin}
    HELM_ADMIN_PASSWORD_VALUE=${HELM_ADMIN_PASSWORD:-$(openssl rand -hex 16)}
    HELM_OAUTH_ENC_KEY_VALUE=${HELM_OAUTH_ENC_KEY:-$(openssl rand -base64 32 | tr -d '\n')}
    DEEPSEEK_API_KEY_VALUE=${DEEPSEEK_API_KEY:-}
    if [[ -z "$DEEPSEEK_API_KEY_VALUE" ]]; then
      if [[ -t 0 ]]; then
        read -r -s -p "DeepSeek API key (optional; press Enter for subscription-only setup): " DEEPSEEK_API_KEY_VALUE
        echo
      else
        IFS= read -r DEEPSEEK_API_KEY_VALUE || true
      fi
    fi

    {
      printf '%s\n' '# Generated by scripts/quickstart.sh --cli. Keep this file private.'
      printf 'HELM_ADMIN_USER=%s\n' "$HELM_ADMIN_USER_VALUE"
      printf 'HELM_ADMIN_PASSWORD=%s\n' "$HELM_ADMIN_PASSWORD_VALUE"
      printf 'HELM_OAUTH_ENC_KEY=%s\n' "$HELM_OAUTH_ENC_KEY_VALUE"
      [[ -z "$DEEPSEEK_API_KEY_VALUE" ]] || printf 'DEEPSEEK_API_KEY=%s\n' "$DEEPSEEK_API_KEY_VALUE"
      printf 'HELM_HOST=0.0.0.0\nHELM_PORT=%s\nHELM_UID=%s\nHELM_GID=%s\n' \
        "$HELM_PORT_VALUE" "$HELM_UID" "$HELM_GID"
    } >.env
    echo "Created .env with generated admin and OAuth encryption credentials."
  else
    printf '%s\n' \
      '# Generated by scripts/quickstart.sh. Finish setup in the browser.' \
      'HELM_HOST=0.0.0.0' \
      "HELM_PORT=$HELM_PORT_VALUE" \
      "HELM_UID=$HELM_UID" \
      "HELM_GID=$HELM_GID" >.env
    echo "Created a private .env for Linux volume ownership and port settings."
  fi
fi

mkdir -p data
if ! docker compose up -d --wait; then
  docker compose logs --tail=100 helm >&2 || true
  exit 1
fi

docker compose ps
if [[ "$mode" == "setup" ]]; then
  port=$(sed -n 's/^HELM_PORT=//p' .env | tail -1)
  port=${port:-8080}
  setup_token=$(sed -n '1p' data/helm-setup-token)
  if [[ ! "$setup_token" =~ ^[0-9a-f]{64}$ ]]; then
    echo "Helm started, but its setup link could not be read from data/helm-setup-token." >&2
    exit 1
  fi
  echo "Helm is ready for first-run setup: http://127.0.0.1:${port}/setup#token=${setup_token}"
else
  echo "Helm is ready. Admin credentials are in .env."
  echo "The root API key is stored once in data/helm-keys.json (mode 0600)."
  echo "Read it now with: cat data/helm-keys.json"
fi
