import { writeFile } from "node:fs/promises";

const registryUrl = "https://registry.npmjs.org/@anthropic-ai/claude-code/latest";
const response = await fetch(registryUrl, {
  headers: { accept: "application/json" },
  signal: AbortSignal.timeout(10_000),
});
if (!response.ok) throw new Error(`Claude CLI version lookup failed: HTTP ${response.status}`);
const body = (await response.json()) as { version?: unknown };
if (typeof body.version !== "string" || !/^\d+\.\d+\.\d+$/.test(body.version)) {
  throw new Error("Claude CLI version lookup returned an invalid semver");
}
const file = "packages/core/src/provider/oauth/claude-client-version.generated.ts";
await writeFile(file, `// Generated by \`pnpm sync:claude-cli\`; do not edit by hand.\nexport const CLAUDE_CODE_CLIENT_VERSION = \"${body.version}\" as const;\n`);
console.log(`[sync:claude-cli] ${body.version}`);
