import { createHash } from "node:crypto";
import { writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CodexModelsResponseSchema } from "../packages/core/src/provider/oauth/codex-model-info.js";

// Build-time script: sync the bundled Codex model catalog AND the Codex client
// version from the openai/codex GitHub repo via the GitHub API. No local
// checkout is involved. NEVER invoked at production runtime; only via
// `pnpm sync:codex-models`.
//
// The upstream /models endpoint gates model slugs by `client_version`
// (minimal_client_version per entry), so the version we present must track the
// latest codex release or entitled accounts silently stop seeing new models.
// codex-rs derives it from CARGO_PKG_VERSION (see models-manager::client_version_to_whole),
// which is stamped from the `rust-vX.Y.Z` release tag; we read the same tag
// from GitHub's "latest release" (which already excludes drafts/prereleases).
//
// Optional: GITHUB_TOKEN raises the unauthenticated rate limit (60 req/h).

const REPO = "openai/codex";
const MODELS_PATH = "codex-rs/models-manager/models.json";
const RELEASE_TAG_PATTERN = /^rust-v(\d+)\.(\d+)\.(\d+)$/;

const modelsTarget = resolve("apps/gateway/src/oauth/codex-models.json");
const versionTarget = resolve("packages/core/src/provider/oauth/codex-client-version.generated.ts");

function githubHeaders(): Record<string, string> {
  const headers: Record<string, string> = {
    Accept: "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
    "User-Agent": "helm-api-sync-codex-models",
  };
  const token = process.env.GITHUB_TOKEN;
  if (token) headers.Authorization = `Bearer ${token}`;
  return headers;
}

async function fetchOk(url: string, init?: RequestInit): Promise<Response> {
  const response = await fetch(url, init);
  if (!response.ok) {
    throw new Error(`${url} -> HTTP ${response.status} ${response.statusText}`);
  }
  return response;
}

async function latestCodexRelease(): Promise<{ version: string; tag: string }> {
  const response = await fetchOk(`https://api.github.com/repos/${REPO}/releases/latest`, {
    headers: githubHeaders(),
  });
  const release = (await response.json()) as {
    tag_name?: unknown;
    draft?: unknown;
    prerelease?: unknown;
  };
  const tag = typeof release.tag_name === "string" ? release.tag_name : "";
  const match = RELEASE_TAG_PATTERN.exec(tag);
  // /releases/latest never returns drafts or prereleases, but a non-rust tag
  // (or a schema change upstream) must fail loudly rather than emit garbage.
  if (!match || release.draft === true || release.prerelease === true) {
    throw new Error(`unexpected latest release for ${REPO}: ${JSON.stringify(release)}`);
  }
  return { version: `${match[1]}.${match[2]}.${match[3]}`, tag };
}

const { version, tag } = await latestCodexRelease();
const versionFile = `// GENERATED by scripts/sync-codex-models.ts — do not edit by hand.
// Source: ${REPO} release tag ${tag} (GitHub releases/latest). Codex sends the
// whole semver (major.minor.patch) as client_version to /models; the endpoint
// gates slugs by it, so re-run \`pnpm sync:codex-models\` when codex ships a release.
export const DEFAULT_OPENAI_CODEX_CLIENT_VERSION = "${version}";
`;
await writeFile(versionTarget, versionFile, "utf8");
console.log(`synced Codex client version ${version} (${tag}) to ${versionTarget}`);

// Pull models.json at the SAME tag so the bundled catalog and client version
// never drift from each other.
const modelsResponse = await fetchOk(
  `https://raw.githubusercontent.com/${REPO}/${encodeURIComponent(tag)}/${MODELS_PATH}`,
  { headers: { "User-Agent": "helm-api-sync-codex-models" } },
);
const parsed = CodexModelsResponseSchema.parse((await modelsResponse.json()) as unknown);
const normalized = `${JSON.stringify({ models: parsed.models }, null, 2)}\n`;
await writeFile(modelsTarget, normalized, "utf8");

const digest = createHash("sha256").update(normalized).digest("hex");
console.log(`synced ${parsed.models.length} Codex models @ ${tag} to ${modelsTarget} (${digest})`);
