import { createHash } from "node:crypto";
import { mkdir, readFile, rename, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { z } from "zod";
import { CodexModelsResponseSchema } from "../packages/core/src/provider/oauth/codex-model-info.js";

export const SOURCES = {
  grok: "https://x.ai/cli/stable",
  claude: "https://registry.npmjs.org/@anthropic-ai/claude-code/latest",
  codex: "https://api.github.com/repos/openai/codex/releases/latest",
} as const;
const MODELS_PATH = "codex-rs/models-manager/models.json";
const MANIFEST_PATH = "config/generated/client-versions.json";
const MODEL_TARGET = "apps/gateway/src/oauth/codex-models.json";
const StableVersion = z.string().regex(/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/);
const Release = z.object({
  tag_name: z.string().regex(/^rust-v\d+\.\d+\.\d+$/),
  draft: z.literal(false),
  prerelease: z.literal(false),
});
const Versions = z.object({ grok: StableVersion, claude: StableVersion, codex: StableVersion });
const Manifest = z.object({
  schemaVersion: z.literal(1),
  versions: Versions,
  sources: z.object({
    grok: z.literal(SOURCES.grok),
    claude: z.literal(SOURCES.claude),
    codex: z.literal(SOURCES.codex),
    codexModels: z.string().url(),
  }),
  codexTag: z.string(),
  catalogSha256: z.string().regex(/^[a-f0-9]{64}$/),
});
type Snapshot = z.infer<typeof Manifest>;
interface Options {
  root?: string;
  fetcher?: typeof fetch;
  token?: string;
}
const digest = (s: string) => createHash("sha256").update(s).digest("hex");
const modelUrl = (tag: string) =>
  `https://raw.githubusercontent.com/openai/codex/${tag}/${MODELS_PATH}`;
const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;
function headers(token?: string): Record<string, string> {
  return {
    Accept: "application/vnd.github+json",
    "User-Agent": "helm-api-client-versions",
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };
}
async function get(url: string, options: Options): Promise<Response> {
  const response = await (options.fetcher ?? fetch)(url, {
    headers: url.startsWith("https://api.github.com/")
      ? headers(options.token)
      : { Accept: "application/json", "User-Agent": "helm-api-client-versions" },
    signal: AbortSignal.timeout(15_000),
    redirect: "error",
  });
  if (!response.ok) throw new Error(`Client version lookup failed: ${url} HTTP ${response.status}`);
  return response;
}
async function latestVersions(options: Options) {
  const [grok, claude, codex] = await Promise.all([
    get(SOURCES.grok, options)
      .then((r) => r.text())
      .then((s) => StableVersion.parse(s.trim())),
    get(SOURCES.claude, options)
      .then((r) => r.json())
      .then(
        (v) =>
          z
            .object({ name: z.literal("@anthropic-ai/claude-code"), version: StableVersion })
            .parse(v).version,
      ),
    get(SOURCES.codex, options)
      .then((r) => r.json())
      .then((v) => Release.parse(v)),
  ]);
  return {
    versions: Versions.parse({ grok, claude, codex: codex.tag_name.slice(6) }),
    tag: codex.tag_name,
  };
}
function versionFiles(versions: z.infer<typeof Versions>) {
  const prefix = "packages/core/src/provider/oauth/";
  const entries = [
    ["grok", "grok-client-version.generated.ts", "XAI_GROK_CLIENT_VERSION"],
    ["claude", "claude-client-version.generated.ts", "CLAUDE_CODE_CLIENT_VERSION"],
    ["codex", "codex-client-version.generated.ts", "DEFAULT_OPENAI_CODEX_CLIENT_VERSION"],
  ] as const;
  return Object.fromEntries(
    entries.map(([provider, file, name]) => [
      prefix + file,
      `// Generated by pnpm sync:client-versions; do not edit by hand.\n// Source: ${SOURCES[provider]}\nexport const ${name} = "${versions[provider]}" as const;\n`,
    ]),
  );
}
async function fetchSnapshot(options: Options) {
  const { versions, tag } = await latestVersions(options);
  const catalog = CodexModelsResponseSchema.parse(await (await get(modelUrl(tag), options)).json());
  if (!catalog.models.length) throw new Error("Codex release catalog is empty");
  const models = json({ models: catalog.models });
  const manifest: Snapshot = {
    schemaVersion: 1,
    versions,
    sources: { ...SOURCES, codexModels: modelUrl(tag) },
    codexTag: tag,
    catalogSha256: digest(models),
  };
  return { ...versionFiles(versions), [MODEL_TARGET]: models, [MANIFEST_PATH]: json(manifest) };
}
async function writeSnapshot(files: Record<string, string>, root: string) {
  // All remote inputs are validated before any destination changes. Stage local
  // writes before renaming; a crash mid-rename is detected by offline hash checks.
  const staged: Array<[string, string]> = [];
  for (const [name, contents] of Object.entries(files)) {
    const target = resolve(root, name);
    await mkdir(dirname(target), { recursive: true });
    const temporary = `${target}.tmp-${process.pid}`;
    await writeFile(temporary, contents);
    staged.push([temporary, target]);
  }
  for (const [temporary, target] of staged) await rename(temporary, target);
}
export async function syncClientVersions(options: Options = {}): Promise<void> {
  await writeSnapshot(await fetchSnapshot(options), options.root ?? process.cwd());
}
export async function checkClientVersions(
  options: Options & { latest?: boolean } = {},
): Promise<void> {
  const root = options.root ?? process.cwd();
  const manifest = Manifest.parse(JSON.parse(await readFile(resolve(root, MANIFEST_PATH), "utf8")));
  if (
    manifest.codexTag !== `rust-v${manifest.versions.codex}` ||
    manifest.sources.codexModels !== modelUrl(manifest.codexTag)
  )
    throw new Error("Codex release/catalog provenance mismatch");
  for (const [name, expected] of Object.entries(versionFiles(manifest.versions))) {
    if ((await readFile(resolve(root, name), "utf8")) !== expected)
      throw new Error(`Client version snapshot mismatch: ${name}`);
  }
  const catalog = await readFile(resolve(root, MODEL_TARGET), "utf8");
  if (digest(catalog) !== manifest.catalogSha256) throw new Error("Codex catalog hash mismatch");
  if (!CodexModelsResponseSchema.parse(JSON.parse(catalog)).models.length)
    throw new Error("Codex catalog is empty");
  if (options.latest) {
    const current = await latestVersions(options);
    if (json(current.versions) !== json(manifest.versions))
      throw new Error(
        `Client versions are stale; run pnpm sync:client-versions. Latest: ${JSON.stringify(current.versions)}`,
      );
    // Same tag alone is insufficient: detect mutable upstream catalog/tag drift.
    const upstream = CodexModelsResponseSchema.parse(
      await (await get(modelUrl(current.tag), options)).json(),
    );
    if (digest(json({ models: upstream.models })) !== manifest.catalogSha256)
      throw new Error("Upstream Codex catalog mismatch; rerun pnpm sync:client-versions");
  }
}
export async function prepareRelease(version: string, options: Options = {}): Promise<void> {
  StableVersion.parse(version);
  const root = options.root ?? process.cwd();
  const path = resolve(root, "package.json");
  const pkg = JSON.parse(await readFile(path, "utf8")) as Record<string, unknown>;
  const current = StableVersion.parse(pkg.version);
  const a = version.split(".").map(Number),
    b = current.split(".").map(Number);
  const difference = a.map((n, i) => n - (b[i] ?? 0)).find((n) => n !== 0) ?? 0;
  if (difference <= 0) throw new Error("Release version must be newer than the current version");
  await syncClientVersions(options);
  await writeFile(path, json({ ...pkg, version }));
}
export async function releaseNeedsFreshness(
  version: string,
  fetcher: typeof fetch = fetch,
  token?: string,
): Promise<boolean> {
  StableVersion.parse(version);
  const r = await fetcher(
    `https://api.github.com/repos/EasyMetaAu/helm-api/git/ref/tags/v${version}`,
    { headers: headers(token), signal: AbortSignal.timeout(15_000), redirect: "error" },
  );
  if (r.status === 404) return true;
  if (!r.ok) throw new Error(`Cannot establish release state: HTTP ${r.status}`);
  z.object({ ref: z.literal(`refs/tags/v${version}`) }).parse(await r.json());
  return false;
}
async function main() {
  const mode = process.argv[2] ?? "--sync";
  const options: Options = { token: process.env.GITHUB_TOKEN };
  if (mode === "--sync") await syncClientVersions(options);
  else if (mode === "--release") await prepareRelease(process.argv[3] ?? "", options);
  else if (mode === "--check" || mode === "--latest")
    await checkClientVersions({ ...options, latest: mode === "--latest" });
  else if (mode === "--release-check") {
    const pkg = JSON.parse(await readFile("package.json", "utf8")) as { version: string };
    await checkClientVersions({
      ...options,
      latest: await releaseNeedsFreshness(pkg.version, fetch, options.token),
    });
  } else throw new Error(`Unknown client version mode: ${mode}`);
  const manifest = Manifest.parse(JSON.parse(await readFile(MANIFEST_PATH, "utf8")));
  console.log(`[client-versions] ${mode}: ${JSON.stringify(manifest.versions)}`);
}
if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href)
  await main();
