import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { CodexModelsResponseSchema } from "../packages/core/src/provider/oauth/codex-model-info.js";

// Build-time script: sync the bundled Codex model catalog AND the Codex client
// version from a LOCAL checkout of openai/codex. NEVER invoked at production
// runtime; only via `pnpm sync:codex-models`.
//
// The upstream /models endpoint gates model slugs by `client_version`
// (minimal_client_version per entry), so the version we present must track the
// latest codex release or entitled accounts silently stop seeing new models.
// codex-rs derives it from CARGO_PKG_VERSION (see models-manager::client_version_to_whole),
// which is stamped from the `rust-vX.Y.Z` release tag; we read the same tag.

const sourceRoot = resolve(process.env.CODEX_REPO ?? "../../codex");
const modelsSource = resolve(sourceRoot, "codex-rs/models-manager/models.json");
const modelsTarget = resolve("apps/gateway/src/oauth/codex-models.json");
const versionTarget = resolve("packages/core/src/provider/oauth/codex-client-version.generated.ts");

const RELEASE_TAG_PATTERN = /^rust-v(\d+)\.(\d+)\.(\d+)$/;

function latestCodexReleaseVersion(): { version: string; tag: string } {
  const output = execFileSync("git", ["-C", sourceRoot, "tag", "--list", "rust-v*"], {
    encoding: "utf8",
  });
  let best: { version: string; tag: string; key: readonly [number, number, number] } | null = null;
  for (const line of output.split("\n")) {
    const tag = line.trim();
    const match = RELEASE_TAG_PATTERN.exec(tag);
    // Pre-release tags (rust-v0.78.0-alpha.6) are intentionally skipped: codex
    // sends the whole semver only, and /models gates on stable releases.
    if (!match) continue;
    const key = [Number(match[1]), Number(match[2]), Number(match[3])] as const;
    if (
      best === null ||
      key[0] > best.key[0] ||
      (key[0] === best.key[0] && key[1] > best.key[1]) ||
      (key[0] === best.key[0] && key[1] === best.key[1] && key[2] > best.key[2])
    ) {
      best = { version: key.join("."), tag, key };
    }
  }
  if (best === null) {
    throw new Error(
      `no rust-vX.Y.Z release tag found in ${sourceRoot}; run \`git fetch --tags\` in the codex checkout`,
    );
  }
  return { version: best.version, tag: best.tag };
}

const { version, tag } = latestCodexReleaseVersion();
const versionFile = `// GENERATED by scripts/sync-codex-models.ts — do not edit by hand.
// Source: openai/codex release tag ${tag}. Codex sends the whole semver
// (major.minor.patch) as client_version to /models; the endpoint gates slugs by
// it, so re-run \`pnpm sync:codex-models\` whenever codex ships a release.
export const DEFAULT_OPENAI_CODEX_CLIENT_VERSION = "${version}";
`;
await writeFile(versionTarget, versionFile, "utf8");
console.log(`synced Codex client version ${version} (${tag}) to ${versionTarget}`);

const raw = await readFile(modelsSource, "utf8");
const parsed = CodexModelsResponseSchema.parse(JSON.parse(raw) as unknown);
const normalized = `${JSON.stringify({ models: parsed.models }, null, 2)}\n`;
await writeFile(modelsTarget, normalized, "utf8");

const digest = createHash("sha256").update(normalized).digest("hex");
console.log(`synced ${parsed.models.length} Codex models to ${modelsTarget} (${digest})`);
